server:
  port: 8080

spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  output:
    ansi:
      enabled: always